org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=E:/jdk-25.0.2

use_modern_java_syntax=false
generate_sources_jar=true
generate_javadocs_jar=false
enable_junit_testing=false
show_testing_output=false

mod_version=2.8.4
root_package=mapwriter
mod_id=mapwriter
mod_name=MapWriter

mod_description=A lightweight minimap mod for Minecraft 1.12.2
mod_authors=Mapwriter,Vectron,moos233
mod_credits=Chrixian,ProfMobius,taelnia,LoneStar144,jk-5
mod_url=
mod_update_json=
mod_logo_path=

mapping_channel=stable
mapping_version=39
use_dependency_at_files=true

minecraft_username=Developer
extra_jvm_args=
extra_tweak_classes=

publish_to_maven=false
publish_to_local_maven=false
maven_name=${mod_name}
maven_url=

release_type=release
publish_with_changelog=false
publish_to_curseforge=false
curseforge_project_id=231387
curseforge_debug=false
publish_to_modrinth=false
modrinth_project_id=
modrinth_sync_readme=false
modrinth_debug=false

change_minecraft_sources=false

use_tags=false
tag_class_name=${root_package}.${mod_id}.Tags

use_access_transformer=false
access_transformer_locations=${mod_id}_at.cfg

use_mixins=false
mixin_booter_version=10.2
generate_mixins_json=false
mixin_configs=${mod_id}
mixin_refmap=mixins.${mod_id}.refmap.json

is_coremod=false
coremod_includes_mod=true
coremod_plugin_class_name=

use_asset_mover=false
asset_mover_version=2.5